You are working on a project aiming to get insights on class information for a few of the lower division computer science course offerings here at UCSD.

You will be working with the CAPES dataset. You will compute a specific statistic for each of the following classes:

- **CSE 11** → total students enrolled (across all course instances)
- **CSE 12** → total CAPEs given (across all course instances)
- **CSE 30** → average study hours per week

For context, when we say a course instance we mean a course offering for a certain quarter. Examples include ["CSE 12 SP23", "CSE 12 WI23", "CSE 12 FA18", etc.]

NOTE:
if you do not have pandas installed, navigate to the jupyter terminal and run 
```
pip install pandas
```
(this will be resolved so users automatically have it downloaded - just noted here for now)

In [7]:
import pandas as pd

# Load the dataset
df = pd.read_csv("capes_dataset_cleaned.csv")

# Display the first few rows
df.head()

,Instructor,Course,Quarter,Total Enrolled,Total CAPEs Given,Percentage Recommended Class,Percentage Recommended Professor,Study Hours per Week,Average GPA Expected,Average GPA Received
0,Butler Elizabeth Annette,AAS 10,SP23,66,48,93.5%,100.0%,2.80,3.84,3.67
1,Butler Elizabeth Annette,AAS 170,SP23,20,7,100.0%,100.0%,2.50,3.86,3.92
2,Jones Ian William Nasser,ANAR 111,SP23,16,3,100.0%,100.0%,3.83,3.67,NaN
3,Shtienberg Gilad,ANAR 115,SP23,26,6,100.0%,83.3%,3.83,3.50,3.07
4,Braswell Geoffrey E.,ANAR 155,SP23,22,9,100.0%,100.0%,5.17,4.00,4.00

Filtering the cse11_dataset to only contain course instances of CSE 11.

In [8]:

# Filter for only CSE 11 course instances
cse11_data = df[df['Course'] == "CSE 11"]

cse11_data.head()

,Instructor,Course,Quarter,Total Enrolled,Total CAPEs Given,Percentage Recommended Class,Percentage Recommended Professor,Study Hours per Week,Average GPA Expected,Average GPA Received
292,Cao Yingjun,CSE 11,SP23,126,43,100.0%,97.6%,8.60,3.47,3.11
1595,Miranda Gregory Joseph,CSE 11,WI23,287,107,91.3%,87.3%,8.54,3.63,3.41
2978,Cao Yingjun,CSE 11,FA22,174,140,97.1%,97.1%,8.63,3.71,3.52
2979,Cao Yingjun,CSE 11,FA22,176,148,97.3%,96.6%,8.30,3.63,3.55
2980,Cao Yingjun,CSE 11,FA22,183,150,95.9%,92.6%,8.60,3.59,3.44

Filtering out all instances that have less than a 20% CAPES response rate. Filter out all instances that have less than 20 students enrolled.

In [4]:

cse11_data = cse11_data[cse11_data['Total Enrolled'] > 20]

# Question to ask, should we just clean total capes given to be %?
# instead of having the user calculate the total capes %?
cse11_data = cse11_data[cse11_data['Total CAPEs Given'] > cse11_data['Total Enrolled'] * 0.2]


cse11_data.head()

,Instructor,Course,Quarter,Total Enrolled,Total CAPEs Given,Percentage Recommended Class,Percentage Recommended Professor,Study Hours per Week,Average GPA Expected,Average GPA Received
292,Cao Yingjun,CSE 11,SP23,126,43,100.0%,97.6%,8.60,3.47,3.11
1595,Miranda Gregory Joseph,CSE 11,WI23,287,107,91.3%,87.3%,8.54,3.63,3.41
2978,Cao Yingjun,CSE 11,FA22,174,140,97.1%,97.1%,8.63,3.71,3.52
2979,Cao Yingjun,CSE 11,FA22,176,148,97.3%,96.6%,8.30,3.63,3.55
2980,Cao Yingjun,CSE 11,FA22,183,150,95.9%,92.6%,8.60,3.59,3.44

Calculate the total number of students enrolled across all CSE 11 course instances. Save this as a variable.

In [9]:
# Total students enrolled across all CSE 11 course instances
total_enrolled_11 = cse11_data['Total Enrolled'].sum()

print(f"CSE 11 - Total Enrolled: {total_enrolled_11}")

CSE 11 - Total Enrolled: 12231

Display the CSE 11 summary.

In [10]:
pd.DataFrame({
    'Class': ['CSE 11'],
    'Total Enrolled': [total_enrolled_11]
})

    Class  Total Enrolled
0  CSE 11           12231

Now apply the same filtering steps to the remaining classes below, then compute the specific statistic for each one.

- **CSE 12**: total CAPEs given
- **CSE 30**: average study hours per week

In [11]:
# CSE 12

# Filter for only CSE 12 course instances
cse12_data = df[df['Course'] == "CSE 12"]

cse12_data = cse12_data[cse12_data['Total Enrolled'] > 20]
cse12_data = cse12_data[cse12_data['Total CAPEs Given'] > cse12_data['Total Enrolled'] * 0.2]

# Total CAPEs given across all CSE 12 course instances
total_capes_given_12 = cse12_data['Total CAPEs Given'].sum()

print(f"CSE 12 - Total CAPEs Given: {total_capes_given_12}")

pd.DataFrame({
    'Class': ['CSE 12'],
    'Total CAPEs Given': [total_capes_given_12]
})

CSE 12 - Total CAPEs Given: 9309

    Class  Total CAPEs Given
0  CSE 12               9309

In [12]:
# CSE 30

# Filter for only CSE 30 course instances
cse30_data = df[df['Course'] == "CSE 30"]

cse30_data = cse30_data[cse30_data['Total Enrolled'] > 20]
cse30_data = cse30_data[cse30_data['Total CAPEs Given'] > cse30_data['Total Enrolled'] * 0.2]

# Average study hours per week across all CSE 30 course instances
avg_study_hours_30 = cse30_data['Study Hours per Week'].mean()

print(f"CSE 30 - Avg Study Hours/Week: {avg_study_hours_30:.2f}")

pd.DataFrame({
    'Class': ['CSE 30'],
    'Avg Study Hours/Week': [avg_study_hours_30]
})

CSE 30 - Avg Study Hours/Week: 11.79

    Class  Avg Study Hours/Week
0  CSE 30             11.793663

You decide that you want to make the following edits:
1. Increase the threshold of users enrolled from a class from 20 to 50 for all of the course instances.
2. Change the CAPEs threshold from 20% to 33%
3. Change from recording "Average GPA Expected" to "Average GPA Recieved"